name: Backend Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install

      - name: Build and deploy backend
        run: |
          npm run build
          npm run deploy
        env:
          NODE_ENV: production
